title: Lekwungen Narratives
subtitle: An archive of Read Alongs in the Lekwungen language
url: "https://jwarrenbc.github.io"
baseurl: "/Lekwungen-Narratives"
author:
  name: Jared Warren

remote_theme: dieghernan/chulapa

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-include-cache # Recommended by Chulapa for performance

chulapa-skin:
  skin: chulapa

defaults:
  - scope:
      path: "" 
    values:
      layout: "default"   # Applies the main theme wrapper to all pages
      header_type: "base" # Sets a standard navigation bar
      show_footer: true   # Ensures the footer appears on all pages
