title: Lekwungen Narratives
subtitle: An archive of Read Alongs in the Lekwungen language
url: "https://jwarrenbc.github.io"
baseurl: "/Lekwungen-Narratives"
author:
  name: Jared Warren

remote_theme: dieghernan/chulapa

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-include-cache

googlefonts:
  - url: "https://fonts.googleapis.com/css2?family=Noto+Sans&display=swap"

chulapa-skin:
  skin: chulapa
  vars:
    font-family-sans-serif: "'Noto Sans', sans-serif"
    font-family-serif: "'Noto Sans', sans-serif"
    font-family-base: "'Noto Sans', sans-serif"
    headings-font-family: "'Noto Sans', sans-serif"

defaults:
  - scope:
      path: "" 
    values:
      layout: "default"   # Applies the main theme wrapper to all pages
      header_type: "base" # Sets a standard navigation bar
      show_footer: true   # Ensures the footer appears on all pages
